# Generated by Django 5.1.3 on 2024-11-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marriage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_photo', models.ImageField(upload_to='groom_photos/')),
                ('groom_first_name', models.CharField(max_length=300)),
                ('groom_last_name', models.CharField(max_length=300)),
                ('groom_father', models.CharField(max_length=300)),
                ('groom_mother', models.CharField(max_length=300)),
                ('groom_relative1', models.CharField(max_length=300)),
                ('groom_relative2', models.CharField(max_length=300)),
                ('groom_relative3', models.CharField(max_length=300)),
                ('bride_photo', models.ImageField(upload_to='bride_photos/')),
                ('bride_first_name', models.CharField(max_length=300)),
                ('bride_last_name', models.CharField(max_length=300)),
                ('bride_father', models.CharField(max_length=300)),
                ('bride_mother', models.CharField(max_length=300)),
                ('bride_relative1', models.CharField(max_length=300)),
                ('bride_relative2', models.CharField(max_length=300)),
                ('bride_relative3', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=300)),
                ('groom_first_name_nepali', models.CharField(max_length=300)),
                ('groom_last_name_nepali', models.CharField(max_length=300)),
                ('groom_father_nepali', models.CharField(max_length=300)),
                ('groom_mother_nepali', models.CharField(max_length=300)),
                ('groom_relative1_nepali', models.CharField(max_length=300)),
                ('groom_relative2_nepali', models.CharField(max_length=300)),
                ('groom_relative3_nepali', models.CharField(max_length=300)),
                ('bride_first_name_nepali', models.CharField(max_length=300)),
                ('bride_last_name_nepali', models.CharField(max_length=300)),
                ('bride_father_nepali', models.CharField(max_length=300)),
                ('bride_mother_nepali', models.CharField(max_length=300)),
                ('bride_relative1_nepali', models.CharField(max_length=300)),
                ('bride_relative2_nepali', models.CharField(max_length=300)),
                ('bride_relative3_nepali', models.CharField(max_length=300)),
                ('date_in_nepali', models.DateField()),
                ('time_in_nepali', models.TimeField()),
                ('venue_nepali', models.CharField(max_length=300)),
            ],
        ),
    ]
